version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "nuget"
    directory: "/tests"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
      
