@Elzik.Breef.Api_HostAddress = http://localhost:5079

Post {{Elzik.Breef.Api_HostAddress}}/breefs
Content-Type: application/json
BREEF-API-KEY: test-key
{
  "url":"https://www.bbc.co.uk/news/articles/cdedkr9439wo"
}
